version: "3.7"
services:
    
      registry:
        restart: always
        image: registry:latest
        ports:
            - 443:5000
        environment:
                REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
                REGISTRY_HTTP_TLS_KEY: /certs/domain.key
                REGISTRY_AUTH: htpasswd
                REGISTRY_HTTP_SECRET: /var/lib/registry/passfile
                REGISTRY_AUTH_HTPASSWD_PATH: /var/lib/registry/passfile
                REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
                REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: redis
                REGISTRY_REDIS_ADDR: redis:6379
        volumes:
            - ./letsencrypt11/registry.lenex.com.ua:/certs/ 
            - ./genpass/:/var/lib/registry/
