version: "3.7"
services:

      genpass:
        build: ./genpass
        container_name: genpass
        volumes:
         - ./genpass:/data
    
      registry:
        restart: always
        image: registry:latest
        ports:
            - 443:5000
        environment:
                REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
                REGISTRY_HTTP_TLS_KEY: /certs/domain.key
                REGISTRY_AUTH: htpasswd
                REGISTRY_AUTH_HTPASSWD_PATH: /var/lib/registry/passfile
                REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        volumes:
            - ./letsencrypt/reg3.lenex.com.ua:/certs 
            - ./genpass/:/var/lib/registry
