    registry:
        restart: always
        image: registry:latest
        ports:
            - 443:5000
        environment:
        REGISTRY_HTTP_TLS_CERTIFICATE: /letsencrypt/live/rep.lenex.com.ua/domain.crt
        REGISTRY_HTTP_TLS_KEY: /letsencrypt/live/rep.lenex.com.ua/domain.key
        REGISTRY_AUTH: htpasswd
        REGISTRY_AUTH_HTPASSWD_PATH: /var/lib/registry/passfile
        REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        volumes:
            - /etc/letsencrypt/live/rep.pearsolution.com.ua:/certs 
            - ./df/:/var/lib/registry
